Repository ubsuny/CP1-24-HW1, pull requests merged in 2024-09, with the labels that each got.

#23 added unit-testing module
  .gitignore
  unit-testing/analyze_tests.py
  unit-testing/prepare_tests.py
  unit-testing/run_unit_tests.py
Labels: enhancement

#29 quantumcode.py
  quantumcode.py
Labels: documentation

#38 quantumcode.py 2.part
  quantumcode.py
Labels: enhancement

#45 Editing devcontainer and qiskit.txt
  .devcontainer/qiskit/devcontainer.json
  Requirements/qiskit.txt
Labels: documentation

#30 Kylemasc917 markdown background on EPR for cp1 24 hw1
  Background-on-EPR-paradox-First-draft.md
Labels: documentation

#56 Testing Bell's Inequality Locally
  Testing-Locally.ipynb
Labels: enhancement

#40 DocumentationBell'sInquality43
  Bell'sInequality43.md
Labels: documentation

#48 Added Documentation for IBM Quantum API
  IBM Quantum API Information.md
Labels: documentation

#55 History of Bell's Theorem (Documentation)
  bell_inequality.md
Labels: documentation

#64 Added setup code to Python file
  Python/quantumcode.py
Labels: enhancement

#80 Unit testing branch, with restored /python directory
  bells-inequality/quantumcode.py
  jupyter-notebooks/Testing-Locally.ipynb
Labels: bug, documentation, architecture

#91 Restructured readme and merged Physics documentation into one single file
  BellsInequalityTheory.md
  HomeWorkDescriptionAndGradingRubric.md
  README.md
Labels: documentation

#103 Made additions to quantumcode.py
  quantumcode_IBM.ipynb
  quantumcode_local.ipynb
Labels: Task_Organization, qiskit
